### PR TITLE
Fix for java.lang.IllegalArgumentException: width and height must be > 0

### PR DESCRIPTION
**Pull request by pschroen**

### CODE REVIEW

**Comment by gilvegliach** [comment]
Hi, thanks for the contribution. Did you see the IllegalArgumentException in any particular conditions? Off the top of my head, I can imagine it happens if you set explicitly width or height to 0, but maybe there is more.

**Comment by pschroen** [comment]
It happens for me with the TextView inside a Toolbar. The contents are dynamically generated and if the TextView is entirely outside of the bounds of the Toolbar then this error is thrown.

**Comment by gilvegliach** [comment]
Looks good to me. I'll merge it and add some optimizations in master (null out the bitmaps if dimensions are set to zero). I think I'll do a patch release over the weekend so you can use the bugfree code. Thanks again! ^_^

**Comment by pschroen** [comment]
Works great, thanks! ;)

**Pull request merged**
